PGVector integration
voxel51/fiftyone-brain pull request #222
Opened 2024-12-20 21:53 UTC by xenophenes

Hi!

These files still need to be polished up and the documentation + similarity test added. I'm opening this draft PR so existing work can be reviewed if desired and so the current progress is known. 

Additional changes will be pushed up to this PR ASAP.

The existing code will have a pre-commit hook performed on it before this PR is marked as ready to merge.

![unnamed](https://github.com/user-attachments/assets/4aa1b71e-d770-4ca8-ab6b-48e9d3083496)
![unnamed1](https://github.com/user-attachments/assets/76d535c8-79c2-49e6-8973-ac1ef2cf4e54)

2024-12-30 18:06 UTC, thesteve0 commented on fiftyone/brain/internal/core/pgvector.py
> +            self._conn.commit()
I am not sure if this is the right place but somewhere you need to create an HNSW index. I think the default values for index density are fine. You should probably ensure that working memory is temporarily set larger than the default. See here
https://github.com/thesteve0/arvix-query/blob/main/sql_commands.sql#L23

Cosine is also a fine distance metric to have as the default.

2024-12-30 18:10 UTC, thesteve0 commented on fiftyone/brain/internal/core/pgvector.py
> +class PgVectorSimilarityConfig(SimilarityConfig):
If you look at the elasticsearch integration they allow for defining the distance metric. We should do the same:
https://github.com/voxel51/fiftyone-brain/blob/e3300432b83adcb515a9179220c7f1f6979d1448/fiftyone/brain/internal/core/elasticsearch.py#L62

We will also need the SSL certs and other connection types that people use with PostgreSQL

2024-12-30 18:11 UTC, thesteve0 commented on fiftyone/brain/internal/core/pgvector.py
> +            self._conn.commit()
Looks like the elasticsearch has an explicit method for index creation
https://github.com/voxel51/fiftyone-brain/blob/e3300432b83adcb515a9179220c7f1f6979d1448/fiftyone/brain/internal/core/elasticsearch.py#L365

2024-12-30 18:20 UTC, thesteve0 commented on fiftyone/brain/internal/core/pgvector.py
Still need an implementation for 

get_embeddings - https://github.com/voxel51/fiftyone-brain/blob/e3300432b83adcb515a9179220c7f1f6979d1448/fiftyone/brain/internal/core/mongodb.py#L375

remove_from_index  - https://github.com/voxel51/fiftyone-brain/blob/e3300432b83adcb515a9179220c7f1f6979d1448/fiftyone/brain/internal/core/mongodb.py#L333

2025-01-07 18:18 UTC, illustris-admin commented on fiftyone/brain/internal/core/pgvector.py
> +            self._conn.commit()
Have added a new method: 'create_hnsw_index' in 'pgvector.py' - Latest commit of 01/07/2025 includes this change

2025-01-07 18:18 UTC, illustris-admin commented on fiftyone/brain/internal/core/pgvector.py
> +class PgVectorSimilarityConfig(SimilarityConfig):
Have updated the method: '_initialize' in 'pgvector.py' to accomodate this functionality - Latest commit of 01/07/2025 includes this change

2025-01-07 18:19 UTC, illustris-admin commented on fiftyone/brain/internal/core/pgvector.py
Have added the method: 'remove_from_index' in 'pgvector.py' to accomodate this functionality - Latest commit of 01/07/2025 includes this change

2025-01-07 19:04 UTC, thesteve0 commented on fiftyone/brain/internal/core/pgvector.py
> +        self.work_mem = work_mem
We are going to need to support the user specifying the index name since they may have already created the index outside of Fiftyone. A table could actually have more than 1 embedding column and therefore would require more than 1 index. They could also create 2 indices on the same embedding column (trying different HNSW parameters) so they need to specify which one to use here. 

We need to be able to use that pre-made index but also delete that index from a fiftyone call. Since we need to do that it would be good to allow the user to specify the name of the index they want created.

2025-01-07 19:04 UTC, thesteve0 commented on fiftyone/brain/internal/core/pgvector.py
> +    def remove_from_index(self, sample_ids):
See comment on init about indices

2025-01-07 19:05 UTC, thesteve0 commented on fiftyone/brain/internal/core/pgvector.py
> +    def cleanup(self):
see comment above in init about indices

2025-01-07 19:07 UTC, thesteve0 commented on fiftyone/brain/internal/core/pgvector.py
> +    def text_to_embedding(self, text):
I assume this is for multimodal embedding search. Is that correct?

2025-01-07 19:08 UTC, thesteve0 commented on fiftyone/brain/internal/core/pgvector.py
> +                FROM embeddings ORDER BY distance ASC LIMIT %s;
What happens here if they don't specify k? Perhaps we should check that they set it or set it to something like 20 by default

2025-01-07 19:49 UTC, illustris-admin commented on fiftyone/brain/internal/core/pgvector.py
> +    def text_to_embedding(self, text):
yes, that is correct

2025-01-09 17:28 UTC, illustris-admin commented on fiftyone/brain/internal/core/pgvector.py
> +                FROM embeddings ORDER BY distance ASC LIMIT %s;
I can set it as a default, and allow for it to be passed as a parameter

2025-01-21 16:32 UTC, prernadh requested changes
Some comments to make this integration consistent with our other vector db integrations.

2025-01-21 16:32 UTC, prernadh commented on fiftyone/brain/internal/core/pgvector.py
> +    def add_to_index(self, embeddings, sample_ids, m=16, ef_construction=64, **kwargs):
Could you add in the following args to add_to_index- 

```
overwrite=True,
allow_existing=True,
warn_existing=False,
reload=True,
```

You can follow a pattern similar to the Qdrant integration [here](https://github.com/voxel51/fiftyone-brain/blob/8658fc8796172da95b9bec45a79b15b72cd6f201/fiftyone/brain/internal/core/qdrant.py#L302)

2025-01-21 16:32 UTC, prernadh commented on fiftyone/brain/internal/core/pgvector.py
> +    def get_embeddings(self):
This PR currently does not support embeddings for patches. Patches are image crops that are generated using bounding box labels. Could you please add this in as well? The qdrant integration can be a good template to follow for it

2025-01-21 18:19 UTC, prernadh commented on fiftyone/brain/internal/core/pgvector.py
> +    def _kneighbors(self, query, k=None, return_dists=False):
Critical: You need to add in the `reverse` argument to _kneighbors. Otherwise `sort_by_similarity` fails

2025-01-21 18:26 UTC, prernadh commented
Sorting by similarity after creating the index is not working- Here is the code snippet I am using
```
import fiftyone as fo
import fiftyone.brain as fob
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
model = foz.load_zoo_model("clip-vit-base32-torch")

pgvector_index = fob.compute_similarity(
    dataset,
    model = model,
    brain_key="pgvector_index",
    backend="pgvector",
    connection_string="connection_string"
)

query_id = dataset.take(1).first().id

# Programmatically construct a view containing the 15 most similar images
view = dataset.sort_by_similarity(query_id, k=15, brain_key="pgvector_index")
```

2025-02-04 23:20 UTC, merged